### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by LostPoE** [MasterFighterr/passthru-hooks-example#3]
Not sure log wise what to post. I think im following the guide. The only thing I changed was "Name" to win10.

OS = ArchLinux/KDE/x11
32GB RAM 

$ pwd
/etc/libvirt/hooks/qemu.d/win10
$ tree
.
├── prepare
│   └── begin
│       ├── 20-reserve-hugepages.sh
│       ├── 30-set-governor.sh
│       └── 40-isolate-cpus.sh
├── release
│   └── end
│       ├── 10-release-hugepages.sh
│       ├── 20-return-cpus.sh
│       └── 30-restore-governor.sh
└── vm-vars.conf

5 directories, 7 files

Error starting domain: internal error: QEMU unexpectedly closed the monitor (vm='win10'): 2023-06-15T00:30:55.831601Z qemu-system-x86_64: unable to map backing store for guest RAM: Cannot allocate memory

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib/python3.11/site-packages/libvirt.py", line 1373, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: QEMU unexpectedly closed the monitor (vm='win10'): 2023-06-15T00:30:55.831601Z qemu-system-x86_64: unable to map backing store for guest RAM: Cannot allocate memory

/etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="rd.driver.pre=vfio-pci amd_iommu=on loglevel=3 quiet"

VM XML:
https://pastebin.com/NWUhVmLF

Thanks

**Comment by LostPoE** [comment]
<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
  <name>win10</name>
  <uuid>b6bfe816-018e-4e40-bac9-5e5003a003bd</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://microsoft.com/win/10"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory>16777216</memory>
  <currentMemory>16777216</currentMemory>
  <memoryBacking>
  <hugepages/>
</memoryBacking>
  <vcpu current="12">12</vcpu>
   <iothreads>1</iothreads>
   <cputune>
   <vcpupin vcpu="0" cpuset="12"/>
   <vcpupin vcpu="1" cpuset="13"/>
   <vcpupin vcpu="2" cpuset="14"/>
   <vcpupin vcpu="3" cpuset="15"/>
   <vcpupin vcpu="4" cpuset="16"/>
   <vcpupin vcpu="5" cpuset="17"/>
   <vcpupin vcpu="6" cpuset="18"/>
   <vcpupin vcpu="7" cpuset="19"/>
   <vcpupin vcpu="8" cpuset="20"/>
   <vcpupin vcpu="9" cpuset="21"/>
   <vcpupin vcpu="10" cpuset="22"/>
   <vcpupin vcpu="11" cpuset="23"/>
   <emulatorpin cpuset="0-11"/>
   <iothreadpin iothread="1" cpuset="0-11"/>
   </cputune>
  <os firmware="efi">
    <type arch="x86_64" machine="q35">hvm</type>
    <boot dev="hd"/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
    <vpindex state="on"/>
<synic state="on"/>
<stimer state="on"/>
<reset state="on"/>
<frequencies state="on"/>
<vendor_id state="on" value="randomid"/>
      <relaxed state="on"/>
      <vapic state="on"/>
      <spinlocks state="on" retries="8191"/>
    </hyperv>
    <vmport state="off"/>
  </features>
  <cpu mode="host-passthrough">
  <cache mode="passthrough"/>
<feature policy="require" name="topoext"/>
    <topology sockets="1" cores="6" threads="2"/>
  </cpu>
  <clock offset="localtime">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
    <timer name="hypervclock" present="yes"/>
  </clock>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="block" device="disk">
      <driver name="qemu" type="raw" cache="none" discard="unmap" io="native"/>
      <source dev="/dev/nvme1n1"/>
      <target dev="sda" bus="sata"/>
    </disk>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw"/>
      <source file="/home/user1/iso/Win10_22H2_English_x64v1.iso"/>
      <target dev="sdb" bus="sata"/>
      <readonly/>
    </disk>
    <controller type="usb" model="qemu-xhci" ports="15"/>
    <controller type="pci" model="pcie-root"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <interface type="network">
      <source network="default"/>
      <mac address="32:34:24:23:4a:a2"/>
      <model type="e1000e"/>
    </interface>
    <console type="pty"/>
    <channel type="spicevmc">
      <target type="virtio" name="com.redhat.spice.0"/>
    </channel>
    <input type="tablet" bus="usb"/>
    <graphics type="spice" port="-1" tlsPort="-1" autoport="yes">
      <image compression="off"/>
    </graphics>
    <sound model="ich9"/>
    <audio id="1" type="jack">
  <input clientName="win10" connectPorts="Navi.*Capture_F[LR]"/>
  <output clientName="win10" connectPorts="Navi.*Playback_F[LR]"/>
</audio>
    <video>
      <model type="qxl"/>
    </video>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0" bus="10" slot="0" function="0"/>
      </source>
    </hostdev>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0" bus="10" slot="0" function="1"/>
      </source>
    </hostdev>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0" bus="10" slot="0" function="2"/>
      </source>
    </hostdev>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0" bus="10" slot="0" function="3"/>
      </source>
    </hostdev>
    <redirdev bus="usb" type="spicevmc"/>
    <redirdev bus="usb" type="spicevmc"/>
  </devices>
  <qemu:commandline>
  <qemu:env name="PIPEWIRE_RUNTIME_DIR" value="/run/user/1000"/>
  <qemu:env name="PIPEWIRE_LATENCY" value="512/48000"/>
  <qemu:arg value="-overcommit"/>
  <qemu:arg value="cpu-pm=on"/>
</qemu:commandline>
</domain>

**Comment by LostPoE** [comment]
Guide looks to be missing steps for a newb like me me. Thanks though.
